//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NkjSoft.Model.Common
{
    using System;
    using System.ComponentModel.Composition;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    [Export("EF", typeof(DbContext))]
    public partial class EnterpriseDevelopmentFxContext : DbContext
    {
        public EnterpriseDevelopmentFxContext()
            : base("name=DefaultConnection")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Users>()
                .HasMany<Roles>(p => p.Roles);
        }

        public DbSet<Applications> Applications { get; set; }
        public DbSet<Memberships> Memberships { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<MenusInRoles> MenusInRoles { get; set; }
        public DbSet<Profiles> Profiles { get; set; }
        public DbSet<Roles> Roles { get; set; }
        public DbSet<Users> Users { get; set; }
    }
}
