//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NkjSoft.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NkjSoft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 版本4.6.0.0:[2010-12-23 22:07:19]
        ///    1. 更新实体生成器(更新到版本(v5.1.3.22),增加对Oracle 的支持(beta),增加对web/app config 的生成;
        ///    2. 
        ///版本4.5.3.30:[2010-12-19 17:28:20]
        ///    1,完善实体验证器,扩展 EntityBase(为完成,慎用);
        ///    2,改进实体生成模块(核心库升级到v4.0,生成器升级到v5.0,设计新的UI界面);
        ///    3. 简化 ColumnAttribute 类,在标记实体的时候,使用简洁的构造函数来初始化. 
        ///    ===---ORM组件---====
        ///     1. ProviderFactory 工厂中,实现一个From()方法,方法接收数据库类型(ProviderType)和一个连接字符串(string)进行实例化 DbEntityProvider 的工作,设置一个bool 参数      (cacheTheProvider),--增加一个重载;
        ///     2. DataContext 增加一个构造函数重载,方法接收数据库类型( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AssamblyInfo {
            get {
                return ResourceManager.GetString("AssamblyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;  
        ///using NkjSoft.Extensions;
        ///using NkjSoft.Extensions.Data;
        ///using NkjSoft.ORM;
        ///using NkjSoft.CommonTypes;
        ///using $ModelNameSpace$;
        ///
        ///namespace $BllNameSpace$
        ///{
        ///    /// &lt;summary&gt;
        ///    ///   对 &lt;see cref=&quot;$BllBaseName$&quot;/&gt; 的描述。 
        ///    /// &lt;/summary&gt;
        ///    /// &lt;typeparam name=&quot;T&quot;&gt;实体类类型&lt;/typeparam&gt;
        ///    public class $BllBaseName$&lt;T&gt; : NkjSoftBllBase&lt;T&gt; where T:class,new()
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 
        ///        /// &lt;/summary&gt;
        ///        public $BllBaseName$()
        ///            : base($Quer [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BllBaseTemplate {
            get {
                return ResourceManager.GetString("BllBaseTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///using System.Linq; 
        ///using System.Data;
        ///using NkjSoft.Extensions;
        ///using NkjSoft.Extensions.Data;
        ///
        ///using NkjSoft.ORM;
        ///using NkjSoft.CommonTypes; 
        ///using $ModelNameSpace$;
        ///
        ///
        ///namespace $BllNameSpace$
        ///{
        ///    /// &lt;summary&gt;
        ///    /// 对 &lt;see cref=&quot;$ClassName$&quot;/&gt; 的描述。无法继承此类。
        ///    /// &lt;/summary&gt;
        ///    public sealed class $ClassName$ : $BllBaseName$&lt;$ModelName$&gt; 
        ///    {
        ///        #region --- 单例实现 ---
        ///        private static readonly $ClassNam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string BllClassTemplate {
            get {
                return ResourceManager.GetString("BllClassTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System; 
        ///using System.Text;
        ///using NkjSoft.ORM;
        ///using NkjSoft.ORM.Core;
        ///using $ModelNameSpace$;
        ///
        ///namespace $ModelNameSpace$
        ///{
        ///        ///&lt;summary&gt;
        ///        /// 表示一个对数据库 $DataBaseName$ 的查询上下文。
        ///        ///&lt;/summary&gt;
        ///        public class $DataBaseName$DataContext : QueryContext
        ///        {
        ///                #region --- 属性 --- 
        ///                $PropertyArea$
        ///
        ///                #endregion
        ///                ///&lt;summary&gt;
        ///                /// 初始化一个新的 $DataBaseName$DataContext 对象。
        ///                ///&lt;/ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DataContextTemplate {
            get {
                return ResourceManager.GetString("DataContextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region --- CodeInfo ---
        ////*
        /// *&lt;CodeGenerated&gt;
        /// * 此代码由 : NkjSoft 实体类 代码生成器生成 ...
        /// * 生成时间 : $DateTime.Now$
        /// * 代码作者 : 俞如凯
        /// * 类型名称 : $ClassName$ 
        /// *&lt;/CodeGenerated&gt;
        /// */
        ///#endregion
        ///
        ///using System; 
        ///using System.Text;
        ///using NkjSoft.ORM.Data;
        ///using NkjSoft.ORM.Data.Mapping; 
        ///
        ///namespace $NameSpace$
        ///{
        ///    ///&lt;summary&gt;
        ///    /// 对 $ClassName$ 的描述。
        ///    ///&lt;/summary&gt;
        ///    [Serializable]
        ///    public partial class $ClassName$ : EntityBase 
        ///    {
        ///        ///&lt;summary&gt;
        ///        /// 实例化新的 &lt;see cref=&quot;$NameS [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DefaultTemplate {
            get {
                return ResourceManager.GetString("DefaultTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4.6.1.1 的本地化字符串。
        /// </summary>
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前模板支持的标记:
        ///	$NameSpace$		--- 命名空间
        ///	$ClassName$		--- 实体类名
        ///	@@Start			--- 起始循环
        ///	$Remark$			--- 属性描述
        ///	$ColumnName$	--- 特性列名
        ///	$DbType$			--- 特性列类型
        ///	$Nullable$		--- 是否允许空
        ///	$PrimaryKey$		--- 是否是主键
        ///	$Identity$			--- 是否自动增长
        ///	$DefaultValue$		--- 默认值
        ///	@@End			--- 结束循环 的本地化字符串。
        /// </summary>
        internal static string TemplateHelpString {
            get {
                return ResourceManager.GetString("TemplateHelpString", resourceCulture);
            }
        }
    }
}
