//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果


using NkjSoft.Core.Models.Security;
using NkjSoft.Framework.Data;
using System;
using System.ComponentModel.Composition;
using System.Linq;

namespace NkjSoft.Core.Data.Repositories.Security.Impl
{
    /// <summary>
    ///   仓储操作层实现——角色信息
    /// </summary>
    [Export(typeof(IRoleRepository))]
    public partial class RoleRepository : EFRepositoryBase<Roles, Guid>, IRoleRepository
    { }
}
