//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NkjSoft.Models.T4
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class ActionDefinition
    {
        public ActionDefinition()
        {
            this.ActionDefinition1 = new HashSet<ActionDefinition>();
        }
    
        public System.Guid Id { get; set; }
        public string Text { get; set; }
        public string Area { get; set; }
        public string ActionName { get; set; }
        public string Controller { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string Icon { get; set; }
        public bool ShowAsMenu { get; set; }
        public string Style { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> ParentNode_Id { get; set; }
    
        public virtual ICollection<ActionDefinition> ActionDefinition1 { get; set; }
        public virtual ActionDefinition ActionDefinition2 { get; set; }
    }
}
