//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NkjSoft.Models.T4
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Applications_Mapping : EntityTypeConfiguration<Applications>
    {
        public Applications_Mapping()
        {                        
              this.HasKey(t => t.ApplicationId);        
              this.ToTable("Applications");
              this.Property(t => t.ApplicationName).HasColumnName("ApplicationName").IsRequired().HasMaxLength(235);
              this.Property(t => t.ApplicationId).HasColumnName("ApplicationId");
              this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(256);
         }
    }
}
