//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NkjSoft.Models.T4
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLogs
    {
        public System.Guid Id { get; set; }
        public string IpAddress { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.Guid> Member_UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
