//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NkjSoft.Models.T4
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Menu_Mapping : EntityTypeConfiguration<Menu>
    {
        public Menu_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("Menu");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.Text).HasColumnName("Text").HasMaxLength(50);
              this.Property(t => t.Action).HasColumnName("Action").HasMaxLength(100);
              this.Property(t => t.Controller).HasColumnName("Controller").HasMaxLength(100);
              this.Property(t => t.Url).HasColumnName("Url").HasMaxLength(500);
              this.Property(t => t.Icon).HasColumnName("Icon").IsUnicode(false).HasMaxLength(50);
              this.Property(t => t.ParentId).HasColumnName("ParentId");
         }
    }
}
