
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NkjSoft.Models.T4
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class ActionDefinition_Mapping : EntityTypeConfiguration<ActionDefinition>
    {
        public ActionDefinition_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("ActionDefinition");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.Text).HasColumnName("Text");
              this.Property(t => t.Area).HasColumnName("Area");
              this.Property(t => t.ActionName).HasColumnName("ActionName").HasMaxLength(256);
              this.Property(t => t.Controller).HasColumnName("Controller").HasMaxLength(256);
              this.Property(t => t.Url).HasColumnName("Url");
              this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(256);
              this.Property(t => t.Icon).HasColumnName("Icon");
              this.Property(t => t.ShowAsMenu).HasColumnName("ShowAsMenu");
              this.Property(t => t.Style).HasColumnName("Style");
              this.Property(t => t.IsDeleted).HasColumnName("IsDeleted");
              this.Property(t => t.AddDate).HasColumnName("AddDate");
              this.Property(t => t.Status).HasColumnName("Status");
              this.Property(t => t.ParentNode_Id).HasColumnName("ParentNode_Id");
              this.HasOptional(t => t.ActionDefinition2).WithMany(t => t.ActionDefinition1).HasForeignKey(d => d.ParentNode_Id);
         }
    }
}
namespace NkjSoft.Models.T4
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Applications_Mapping : EntityTypeConfiguration<Applications>
    {
        public Applications_Mapping()
        {                        
              this.HasKey(t => t.ApplicationId);        
              this.ToTable("Applications");
              this.Property(t => t.ApplicationName).HasColumnName("ApplicationName").IsRequired().HasMaxLength(235);
              this.Property(t => t.ApplicationId).HasColumnName("ApplicationId");
              this.Property(t => t.Description).HasColumnName("Description").HasMaxLength(256);
              this.Property(t => t.IsDeleted).HasColumnName("IsDeleted");
              this.Property(t => t.AddDate).HasColumnName("AddDate");
              this.Property(t => t.Status).HasColumnName("Status");
         }
    }
}
namespace NkjSoft.Models.T4
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class LoginLogs_Mapping : EntityTypeConfiguration<LoginLogs>
    {
        public LoginLogs_Mapping()
        {                        
              this.HasKey(t => t.Id);        
              this.ToTable("LoginLogs");
              this.Property(t => t.Id).HasColumnName("Id");
              this.Property(t => t.IpAddress).HasColumnName("IpAddress").IsRequired().HasMaxLength(15);
              this.Property(t => t.IsDeleted).HasColumnName("IsDeleted");
              this.Property(t => t.AddDate).HasColumnName("AddDate");
              this.Property(t => t.Member_UserId).HasColumnName("Member_UserId");
              this.Property(t => t.Status).HasColumnName("Status");
              this.HasOptional(t => t.Users).WithMany(t => t.LoginLogs).HasForeignKey(d => d.Member_UserId);
         }
    }
}
namespace NkjSoft.Models.T4
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Memberships_Mapping : EntityTypeConfiguration<Memberships>
    {
        public Memberships_Mapping()
        {                        
              this.HasKey(t => t.UserId);        
              this.ToTable("Memberships");
              this.Property(t => t.ApplicationId).HasColumnName("ApplicationId");
              this.Property(t => t.UserId).HasColumnName("UserId");
              this.Property(t => t.Password).HasColumnName("Password").IsRequired().HasMaxLength(128);
              this.Property(t => t.PasswordFormat).HasColumnName("PasswordFormat");
              this.Property(t => t.PasswordSalt).HasColumnName("PasswordSalt").IsRequired().HasMaxLength(128);
              this.Property(t => t.Email).HasColumnName("Email").HasMaxLength(256);
              this.Property(t => t.PasswordQuestion).HasColumnName("PasswordQuestion").HasMaxLength(256);
              this.Property(t => t.PasswordAnswer).HasColumnName("PasswordAnswer").HasMaxLength(128);
              this.Property(t => t.IsApproved).HasColumnName("IsApproved");
              this.Property(t => t.IsLockedOut).HasColumnName("IsLockedOut");
              this.Property(t => t.CreateDate).HasColumnName("CreateDate");
              this.Property(t => t.LastLoginDate).HasColumnName("LastLoginDate");
              this.Property(t => t.LastPasswordChangedDate).HasColumnName("LastPasswordChangedDate");
              this.Property(t => t.LastLockoutDate).HasColumnName("LastLockoutDate");
              this.Property(t => t.FailedPasswordAttemptCount).HasColumnName("FailedPasswordAttemptCount");
              this.Property(t => t.FailedPasswordAttemptWindowStart).HasColumnName("FailedPasswordAttemptWindowStart");
              this.Property(t => t.FailedPasswordAnswerAttemptCount).HasColumnName("FailedPasswordAnswerAttemptCount");
              this.Property(t => t.FailedPasswordAnswerAttemptWindowsStart).HasColumnName("FailedPasswordAnswerAttemptWindowsStart");
              this.Property(t => t.Comment).HasColumnName("Comment").HasMaxLength(256);
              this.Property(t => t.IsDeleted).HasColumnName("IsDeleted");
              this.Property(t => t.AddDate).HasColumnName("AddDate");
              this.Property(t => t.Status).HasColumnName("Status");
              this.HasRequired(t => t.Applications).WithMany(t => t.Memberships).HasForeignKey(d => d.ApplicationId);
              this.HasRequired(t => t.Users).WithOptional(t => t.Memberships);
         }
    }
}
namespace NkjSoft.Models.T4
{
    #pragma warning disable 1573
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Common;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration;
    using System.Data.Entity.Infrastructure;
    
    internal partial class Menu_Mapping : EntityTypeConfiguration<Menu>
    {
        public Menu_Mapping()
        {                        
              this.HasKey(t => t.Id);        
